# [http.middlewares]
#  [http.middlewares.oauth.forwardAuth]
#    address = "http://oauth:4181"
#    trustForwardHeader = true
#    authResponseHeaders = ["X-Forwarded-User"]

[http.middlewares]
  [http.middlewares.oauth.basicAuth]
         usersFile = "/rules/user"

