#[http.routers]
#  [http.routers.pihole-rtr]
#      entryPoints = ["https"]
#      rule = "Host(`pihole.xiongnas.top`)"
#      service = "pihole-svc"
#      middlewares = ["secure-chain", "add-admin"]
#      [http.routers.pihole-rtr.tls]
#        certresolver = "dns-cloudflare"

#[http.middlewares]
#  [http.middlewares.add-admin.addPrefix]
#    prefix = "/admin"

#[http.services]
#  [http.services.pihole-svc]
#    [http.services.pihole-svc.loadBalancer]
#      passHostHeader = true
#      [[http.services.pihole-svc.loadBalancer.servers]]
#        url = "http://10.0.1.5:80" # or whatever your external host's IP:port is
